steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - --branch=master
      - https://github.com/shahakash277/idurar-erp-crm.git
    dir: /workspace

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔑 Setting up SSH key..."
        mkdir -p /root/.ssh
        echo "$_SSH_KEY" > /root/.ssh/crm-demo-key
        chmod 600 /root/.ssh/crm-demo-key
        echo "Host 104.154.114.203
          IdentityFile /root/.ssh/crm-demo-key
          User akash_contextqa_com
          StrictHostKeyChecking no" > /root/.ssh/config
        chmod 600 /root/.ssh/config

        echo "📥 Copying latest code to VM..."
        ssh 104.154.114.203 "rm -rf ~/idurar-erp-crm"
        scp -r /workspace/idurar-erp-crm/ 104.154.114.203:~/idurar-erp-crm

        echo "🚀 Deploying with docker-compose on VM..."
        ssh 104.154.114.203 "
          cd ~/idurar-erp-crm &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml down &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml build --no-cache &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml up -d
        "

serviceAccount: "cloud-build-service-account@cqa-portal-server-staging.iam.gserviceaccount.com"
