steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔄 Pulling latest code from GitHub on VM..."
        gcloud compute ssh crm-demo-github --zone=us-central1-c --command="
          cd ~/idurar-erp-crm &&
          git reset --hard &&
          git pull origin master &&
          docker-compose pull &&
          docker-compose up -d
        "
serviceAccount: "cloud-build-service-account@cqa-portal-server-staging.iam.gserviceaccount.com"
