steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - --branch=master
      - https://github.com/shahakash277/idurar-erp-crm.git
    dir: /workspace

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "📥 Copying latest code to VM..."
        ssh -i /workspace/crm-demo-key -o StrictHostKeyChecking=no akash_contextqa_com@104.154.114.203 "rm -rf ~/idurar-erp-crm"
        scp -i /workspace/crm-demo-key -o StrictHostKeyChecking=no -r /workspace/idurar-erp-crm/ akash_contextqa_com@104.154.114.203:~/idurar-erp-crm

        echo "🚀 Deploying with docker-compose on VM..."
        ssh -i /workspace/crm-demo-key -o StrictHostKeyChecking=no akash_contextqa_com@104.154.114.203 "
          cd ~/idurar-erp-crm &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml down &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml build --no-cache &&
          docker-compose -f ~/idurar-erp-crm/docker-compose.yml up -d
        "

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔑 Copying SSH key to workspace..."
        echo "$_SSH_KEY" > /workspace/crm-demo-key
        chmod 600 /workspace/crm-demo-key

serviceAccount: "cloud-build-service-account@cqa-portal-server-staging.iam.gserviceaccount.com"
